# Generated by Django 5.1.1 on 2024-09-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100, verbose_name='player1')),
                ('player2', models.CharField(max_length=100, verbose_name='player2')),
                ('player3', models.CharField(max_length=100, verbose_name='player3')),
                ('player4', models.CharField(max_length=100, verbose_name='player4')),
                ('player5', models.CharField(max_length=100, verbose_name='player5')),
                ('player6', models.CharField(max_length=100, verbose_name='player6')),
                ('player7', models.CharField(max_length=100, verbose_name='player7')),
                ('player8', models.CharField(max_length=100, verbose_name='player8')),
                ('player9', models.CharField(max_length=100, verbose_name='player9')),
                ('player10', models.CharField(max_length=100, verbose_name='player10')),
                ('player11', models.CharField(max_length=100, verbose_name='player11')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.matchlist')),
            ],
        ),
    ]
