# Generated by Django 5.1.1 on 2024-10-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerslist',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player10',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player11',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player5',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player6',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player7',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player8',
        ),
        migrations.RemoveField(
            model_name='playerslist',
            name='player9',
        ),
    ]
