# Generated by Django 5.1.1 on 2024-10-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_playerslist_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslist',
            name='players',
            field=models.TextField(blank=True, null=True),
        ),
    ]
